<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>1.2.2</Version>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net6.0'">
		<DefineConstants>NET6;</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<DefineConstants>NET8;</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.*" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.*" />
	</ItemGroup>
</Project>